// <auto-generated />
using DinerBlazorServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DinerBlazorServer.Migrations
{
    [DbContext(typeof(DinerDbContext))]
    partial class DinerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("JCsDiner.SimulatorResults", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualAveragePartySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageEntryTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfCooks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfCustomers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfTables")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfWaiters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetAveragePartySize")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
